# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - whatsapp

on:
  push:
    branches:
      - salah
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v4

      # Étape 2 : Configurer .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Étape 3 : Restaurer les dépendances
      - name: Restore dependencies
        run: dotnet restore WebappWhatsapp/WebappWhatsapp.sln

      # Étape 4 : Construire la solution
      - name: Build with dotnet
        run: dotnet build WebappWhatsapp/WebappWhatsapp.sln --configuration Release

      # Étape 5 : Publier les fichiers de l'application
      - name: dotnet publish
        run: dotnet publish WebappWhatsapp/WebappWhatsapp.sln -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      # Étape 6 : Téléverser l'artifact pour le job de déploiement
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Étape 1 : Télécharger l'artifact depuis le job de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # Étape 2 : Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 3 : Déployer l'application sur Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'whatsapp'
          slot-name: 'production'
          package: .
